#!/bin/sh

# PBC 450 - Rew Kim

# Complete the following on curie
# Sets the current directory to the folder containing all the files of interest
cd ~/PBC450_2025/soil_metagenomics/20251107_1254_MN29288_FBE86142_e0306a7f/pod5/demux/

# Runs Nanoplot on barcode 1 data and outputs it as barcode01_np
NanoPlot -o barcode01_np --fastq e0306a7f-0f47-436a-bfef-23e64d0532f5_SQK-RBK114-24_barcode01.fastq

# Runs epi2me wf-metagenomics pipeline on barcode 1 data using nextflow. This outputs as barcode01_metagen
nextflow run epi2me-labs/wf-metagenomics --fastq e0306a7f-0f47-436a-bfef-23e64d0532f5_SQK-RBK114-24_barcode01.fastq --out_dir barcode01_metagen

# Complete the following on a new terminal window
# Set current directory to file save location
cd ~/Desktop

# Transfer Nanoplot output to file save location through curie server
scp -r gjf5502@10.2.0.53:/home/gjf5502/PBC450_2025/soil_metagenomics/20251107_1254_MN29288_FBE86142_e0306a7f/pod5/demux/barcode01_np .

# Transfer epi2me wf-metagenomics pipeline output to file save location through curie server
scp -r gjf5502@10.2.0.53:/home/gjf5502/PBC450_2025/soil_metagenomics/20251107_1254_MN29288_FBE86142_e0306a7f/pod5/demux/barcode01_metagen

# Thank you so much, Suzy!
